config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :questions do
    member do
      put 'hide'
    end
  end

  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: %i[index]
  resources :hashtags, only: %i[show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_many :question_hashtags, dependent: :destroy
  has_many :questions, through: :question_hashtags

  validates :name, presence: true, uniqueness: true
end

app/models/question.rb
class Question < ApplicationRecord
  REGEXP_FOR_TAGS = /#[[:word:]-]+/
  validates :body, presence: true, length: { maximum: 280 }

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :question_hashtags
  has_many :hashtags, through: :question_hashtags, dependent: :destroy

  before_save :downcase_hashtags_body_and_answer
  after_save_commit :find_and_create_hashtags

  private

  def downcase_hashtags_body_and_answer
    body.gsub!(REGEXP_FOR_TAGS) { |tag| tag&.downcase }
    answer&.gsub!(REGEXP_FOR_TAGS) { |tag| tag&.downcase }
  end

  def find_and_create_hashtags
    question_hashtags = "#{body} + #{answer}".scan(REGEXP_FOR_TAGS)

    self.hashtags = question_hashtags.uniq.map do |tag|
      Hashtag.find_or_create_by(name: tag.downcase)
    end
  end

  def self.most_answered_users_ids
    where.not(answer: nil).group(:user_id).count.sort_by(&:last).reverse.to_h.keys
  end
end

app/models/question_hashtag.rb
class QuestionHashtag < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question

  def self.popular_hashtad_ids
    group(:hashtag_id).count(:id).sort_by(&:last).reverse.to_h.keys
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  before_validation :downcase_nickname
  before_validation :downcase_email

  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[\w\-.]+@[\w\-]+\.[a-z]+\z/i }

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 40 },
                       format: { with: /\A\w+\z/i }

  validates :navbar_color, format: { with: /\A#[[:xdigit:]]{6}\z/ }

  has_many :questions, dependent: :delete_all

  include Gravtastic
  gravtastic(secure: true, filetype: :png, size: 100, default: 'retro')

  def to_param
    nickname
  end

  private

  def downcase_nickname
    nickname&.downcase!
  end

  def downcase_email
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'Вам сюда нельзя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: %i[update destroy edit hide]
  before_action :set_question_for_current_user, only: %i[edit update destroy hide]

  def create
    question_params = params.require(:question).permit(:body, :user_id)

    @question = Question.new(question_params)

    @question.author = current_user

    if @question.save && check_captcha(@question)

      redirect_to user_path(@question.user), notice: 'Новый вопрос создан!'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы вопроса'

      render :new
    end
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    if @question.update(question_params)

      redirect_to user_path(@question.user), notice: 'Обновили вопрос!'
    else
      flash.now[:alert] = 'При попытке сохранить вопрос возникли ошибки'

      render :edit
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Вопрос удалён!'
  end

  def show
    @question = Question.find(params[:id])
  end

  def index
    @questions = Question.order(created_at: :desc).first(15)
    @users = User.order(created_at: :desc).last(10)
    @top_answered_users = Question.most_answered_users_ids.map { |id| User.find(id) }.first(5)
    @hashtags = QuestionHashtag.popular_hashtad_ids.map { |id| Hashtag.find(id) }.first(10)
  end

  def new
    @user = User.find_by!(nickname: params[:user_id])
    @question = Question.new(user: @user)
  end

  def edit; end

  def hide
    @question.update(hidden: true)

    redirect_to question_path, notice: 'Скрыли вопрос!'
  end

  private

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы вошли на сайт'
    else
      flash.now[:alert] = 'Неправильный email или пароль'
      render :new
    end
  end

  def new; end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Вы вышли из аккаунта'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy show]
  before_action :authorize_user, only: %i[edit update destroy]

  def create
    user_params = params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation
    )

    @user = User.create(user_params)

    if @user.save

      session[:user_id] = @user.id

      redirect_to root_path, notice: 'Вы успешно зарегистрировались'
    else
      flash.now[:alert] = 'Вы неправильно заполнили поля формы регистрации'

      render :new
    end
  end

  def new
    session[:current_time] = Time.now
    @user = User.new
  end

  def edit; end

  def update
    if @user.update(user_params)

      session[:user_id] = @user.id

      redirect_to root_path, notice: 'Данные пользователя обновлены'
    else
      flash.now[:alert] = 'При попытке сохранить пользователя возникли ошибки'
      render :edit
    end
  end

  def destroy
    @user.destroy

    session.delete(:user_id)

    redirect_to root_path, notice: 'Пользователь удалён'
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
    @unanswered_questions = @questions.select { |m| m.answer.nil? }
    @answered_questions = @questions.select { |m| !m.answer.nil? }
  end

  private

  def authorize_user
    redirect_with_alert unless @user == current_user
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :navbar_color, :password, :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, few, many)
    return many if (count % 100).between?(11, 14)

    case count % 10
    when 1 then one
    when 2..4 then few
    else
      many
    end
  end

  def navbar_color_now
    return '#370617' unless current_user.present?

    current_user.navbar_color
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def text_with_link_hashtag(hashtags, text)
    hashtags.each do |tag|
      text.gsub!(/#{tag.name}/) { |name| link_to name, hashtag_path(tag) }
    end

    simple_format(text)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_nickname(user)
    "@#{user.nickname}"
  end
end

app/views/hashtags/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Вопросы с хэштегом <b class="text-red"><%= @hashtag.name %></b></h2>  
</div>

<% @hashtag.questions.uniq.each do |question| %>
  <div class="mt-sm container">
    <p class="mb text-sm text-grey">
      Вопрос <%= link_to "##{question.id}", question_path(question) %>
      для юзера <%= link_to "@#{question.user.nickname}", user_path(question.user) %>
    </p>      
    <%= render question %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>Askme</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_importmap_tags %>
    </head>

    <body>
      <div class="wrapper">
        <div class="navbar" style="background-color: <%= navbar_color_now %>">
          <p class="title-sm text-bold"><%= link_to "Ask me!", root_path %></p>
          <div>
            <% if current_user.present? %>
              <%= link_to "#{display_nickname(current_user)}", 
                  edit_user_path(current_user), class: 'mr-sm' %>
              <%= button_to "Выйти", session_path, method: :delete %>
            <% else %>
              <%= link_to "Регистрация", new_user_path, class: 'button button-yellow mr-sm' %>
              <%= link_to "Вход", new_session_path, class: 'button button-yellow' %>
            <% end %>
          </div>
        </div>

        <% if flash[:notice].present? %>
          <p class="mb mt message message-notice"><%= flash[:notice] %></p>
        <% elsif flash[:alert].present? %>
          <p class="mb mt message message-alert"><%= flash[:alert] %></p>
        <% end %>
        <%= yield %>
      </div>
    </body>
  </html>

app/views/questions/_form.html.erb
  <%= form_with model: question, data: {turbo: false} do |form| %>
    <%= form.hidden_field :user_id %>

    <p><%= form.label :body, 'Текст вопроса' %></p>
    <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

    <p class="mb"><%= recaptcha_tags(noscript: false) unless current_user.present? %></p>

    <% if question.persisted? %>
      <p class="mt"><%= form.label :answer, 'Ответ' %></p>
      <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
    <% end %>

    <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>
  <% end %>

app/views/questions/_question.html.erb
  <div class="mb-sm">
    <%= text_with_link_hashtag(question.hashtags, question.body) %>
  </div>

  <% if question.answer.present? %>
    <div class="text-sm text-grey">Ответ:</div>
    <div class="mb-sm text-dark-red">
      <%= text_with_link_hashtag(question.hashtags, question.answer) %>
    </div>
  <% end %>

  <div class="text-sm question-footer">
    <div class="text-grey">
      <p><%= l(question.created_at, format: :short) %>
        | Вопрос от

        <% if question.author.present?%>
          <%= link_to "#{display_nickname(question.author)}", 
                  user_path(question.author), class: 'mr-sm' %>
        <%else%>
          Анонимного пользователя
        <%end%>
      </p>
    </div>

    <div>
      <% if question.user == current_user %>
        <% unless question.hidden? %>
          <%= button_to fa_icon('eye-slash'), hide_question_path(question), method: :put, 
          title: 'Скрыть вопрос' %>
        <% end %>
        <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>

        <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Изменить вопрос', class: 'mr-sm' %>

        <%= button_to fa_icon('trash-o'), question_path(question), method: :delete, 
        title: 'Удалить вопрос', form: {data: {turbo_confirm: 'Точно удалить вопрос?'}} %>
      <% end %>
      <%= link_to fa_icon('list'), questions_path, title: 'Все вопросы' %>
    </div>

  </div>

app/views/questions/edit.html.erb
  
  <div class="container">
    <h2 class="title-lg mb">Редактируем вопрос <%= @question.id %></h2>

    <% if @question.errors.any? %>
      <div class="mt">
        <% @question.errors.full_messages.each do |message| %>
          <p class="mb-sm text-red"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <%= render 'form', question: @question %>

    <p class="mt"><%= link_to 'Вернуться', :back %></p>
  </div>

app/views/questions/index.html.erb
  <% if @users.any? %> 
    <div class="container">
      
      <% if @top_answered_users.any? %> 
        <h2 class="title-lg mb">
          ТОП 5 отвечающих
        </h2>
        <div class="users-box">

          <% @top_answered_users.each do |user| %>
          <%= render partial: 'users/user_avatar', locals: {user: user} %>
          <% end %>
      
        </div>
      <% end %>
      
      <h2 class="title-lg mb">
        Недавно добавились
      </h2>
      <div class="users-box">

        <% @users.each do |user| %>
          <%= render partial: 'users/user_avatar', locals: {user: user} %>
        <% end %>
      
      </div>
    </div>
  <% else %>
    <div class="container text-center">
      <p class="title-sm text-grey">
        Некого спрашивать:( Скорее регистрируйся!
      </p>

      <div class="mt-lg mb-lg fa-5x text-light-grey">
        <%= fa_stacked_icon 'users', base: 'square-o' %>
      </div>    
    </div>  
  <% end %>

  <% if @hashtags.any? %> 
    <div class="mt-sm container">
      <p class="text-sm">
   
        <% @hashtags.each do |hashtag| %>
          <b class="text-red">
            <%= link_to hashtag.name, hashtag_path(hashtag) %>
          </b>
        <% end %>

      </p>  
    </div>
  <% end %>

  <% if @questions.any? %> 
    <div class="container mt">
      <h2 class="title-lg">
        <%= inclination(@questions.count, 'Последний', 'Последние', 'Последние') %>
        <%= @questions.count %>
        <%= inclination(@questions.count, 'вопрос', 'вопроса', 'вопросов') %>
      </h2>
    </div>

    <% @questions.each do |question| %>
      <div class="mt-sm container">
        <p class="mb text-sm text-grey">
          Вопрос <%= link_to "##{question.id}", question_path(question) %>
          для юзера <%= link_to "@#{question.user.nickname}", user_path(question.user) %>
        </p>
        <%= render question %>
      </div>
    <% end %>
  <% end %>

app/views/questions/new.html.erb
  <div class="container">
    <h2 class="title-lg mb-sm">Новый вопрос</h2>
    <p class="mb">для <%= link_to "@#{@question.user.nickname}", user_path(@question.user) %></p>

    <% if @question.errors.any? %>
      <div class="mt">
        <% @question.errors.full_messages.each do |message| %>
          <p class="mb-sm text-red"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <%= render 'form', question: @question %>

    <p class="mt"><%= link_to 'Вернуться', :back %></p>
  </div>

app/views/questions/show.html.erb
  <div class="container">
    <h2 class="title-lg mb">Вопрос <%= @question.id %></h2>
    <p class="mt-sm"><%= link_to "Все вопросы @#{@question.user.nickname}", user_path(@question.user) %></p>
  </div>

  <div class="mt-sm container">
    <%= render 'question', question: @question %>
  </div>

app/views/users/_no_questions.html.erb
  
  <div class="container text-center">
    <p class="title-sm text-grey">
      У этого пользователя пока никто ничего не спросил
    </p>

    <div class="mt-lg mb-lg fa-5x text-light-grey">
      <%= fa_stacked_icon 'question', base: 'square-o' %>
    </div>

    <%= link_to "Дай, спрошу!", new_question_path(user_id: user),
    class: 'button button-main' %>
  </div>

app/views/users/_user_avatar.html.erb
<% background_class = "users-box-user-bg#{user.id % 5}" %>

  <div class="users-box-user <%= background_class %> rounded mr ml">
    <a href="<%= user_path(user) %>">
      <%= image_tag user.gravatar_url, title: "@#{user.nickname}", class: 'rounded' %>
    </a>
  </div>

app/views/users/edit.html.erb
  <div class="container">
    <h2 class="title">Редактирование профиля</h2>

    <div class="mt">
      <p><%= image_tag @user.gravatar_url, title: "@#{@user.nickname}", class: 'rounded' %></p>
      <p class="text-sm">Чтобы добавить или поменять аватар — зарегистрируйтесь на <%= link_to "Gravatar", 'https://gravatar.com' %> и загрузите фото</p>
    </div>

    <% if @user.errors.any? %>
      <div class="mt">
        <% @user.errors.full_messages.each do |message| %>
          <p class="mb-sm text-red"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="mt">
      <%= form_with model: @user, data: {turbo: false} do |form| %>
        <p><%= form.label :name, 'Имя' %></p>
        <p><%= form.text_field :name, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
        <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :navbar_color, 'Цвет шапки сайта' %></p>
        <p><%= form.color_field :navbar_color, class: 'form-text-field' %></p>

        <p class="mt-lg text-sm">Если не хотите менять пароль — оставьте эти поля пустыми!</p>

        <p class="mt"><%= form.label :password, 'Пароль' %></p>
        <p><%= form.password_field :password, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :password_confirmation, 'Подтверждение пароля' %></p>
        <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

        <p class="mt-lg">
          <%= form.submit "Сохранить", class: 'button button-main' %>
          <span class="text-sm">или <%= link_to "вернуться", :back %></span>
        </p>
      <% end %>
    </div>

    <div class="mt-lg">
      <%= button_to "Удалить профиль", user_path(@user), method: :delete,
      form: {data: {turbo_confirm: "Вы точно хотите удалить свой профиль?"}},
      class: 'text-red text-sm' %>
    </div>
  </div>

app/views/users/new.html.erb
  
  <div class="container">
    <h2 class="title">Присоединяйся и спрашивай!</h2>

    <% if @user.errors.any? %>
      <div class="mt">
        <% @user.errors.full_messages.each do |message| %>
          <p class="mb-sm text-red"><%= message %></p>
        <% end %>
      </div>
    <% end %>

    <div class="mt">
      <%= form_with model: @user, data: {turbo: false} do |form| %>
        <p><%= form.label :name, 'Ваше имя' %></p>
        <p><%= form.text_field :name, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :nickname, 'Ник на сайте' %></p>
        <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :email %></p>
        <p><%= form.text_field :email, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :password %></p>
        <p><%= form.password_field :password, class: 'form-text-field' %></p>

        <p class="mt"><%= form.label :password_confirmation %></p>
        <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

        <p><%= form.submit "Зарегистрироваться", class: 'button button-main mt-lg' %></p>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
  
  <div class="user-box">
    <h2 class="title-lg mt-lg"><%= @user.name %></h2>

    <div class="mt">
      <%= render partial: 'users/user_avatar', locals: {user: @user} %>
    </div>

    <% if current_user == @user %>
      <p class="mt mb-lg">
        <%= link_to fa_icon('pencil'), edit_user_path(@user) %>
      </p>
    <% end %>

    <p class="text-bold mt mb-lg">@<%= @user.nickname %></p>

  </div>

  <% if @questions.any? %>
    <div class="container">
      <%= link_to 'Спроси меня', new_question_path(user_id: @user.nickname),
      class: 'button button-yellow' %>

      <p class="mt">
        <%= render 'questions/form', question: @question %>
      </p>
    </div>

    <div class="container mt-sm">
      <h2 class="title-lg">
        <% if @answered_questions.present?%>
          Ответил на <%= @answered_questions.count %> 
          <%= inclination(@answered_questions.count, 'вопрос', 'вопроса', 'вопросов') %>
          из <%= @questions.count %>
        <% else %>
          Вопросы без ответа:
        <% end %>
      </h2>
    </div>

    <% if current_user == @user && @unanswered_questions.present? %>
      <div class="container mt-sm">
        <h2 class="title-lg text-dark-red">
          Осталось ответить на 
          <%= @unanswered_questions.count %>
          <%= inclination(@unanswered_questions.count, 'вопрос!', 'вопроса!', 'вопросов!') %>
        </h2>
      </div>
    <% end %>

    <% @questions.each do |question| %>
      <div class="mt-sm container">
        <%= render question %>
      </div>
    <% end %>
  <% else %>
    <%= render partial: 'no_questions', locals: {user: @user} %>
  <% end %>